name: Deploy to WP Engine
on:
  push:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v4
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        WPE_ENV: vivwebs
  cascading-merge:
    permissions: write-all
    name: Cascading Merge
    runs-on: ubuntu-latest
    steps:
      # merge github main to stage
      - name: Cascading Merge
        uses: mheap/cascading-merge-action@v1.0.1
        with:      
          token: ${{ github.token }}
          branches: |
            main
            stage
      # merge github dev to stage
      - name: Cascading Merge2
        uses: mheap/cascading-merge-action@v1.0.1
        with:
          branches: |
            main
            dev
      - name: Deploy to WP Engine fom git stage to wpe stage
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy to WP Engine stage
          repo: ${{ github.repository }}
          token: ${{ github.token }}
          ref: refs/heads/stage
      - name: Deploy to WP Engine fom git dev to wpe dev
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy to WP Engine dev
          repo: ${{ github.repository }}
          token: ${{ github.token }}
          ref: refs/heads/dev