name: Deploy to WP Engine
on:
  push:
    branches:
     - main
jobs:
  cascading-merge:
    permissions: write-all
    name: Cascading Merge
    runs-on: ubuntu-latest
    steps:
      # merge github main to stage
      - name: Cascading Merge
        uses: sovabarmak/cascading-merge-action@v1.0.10
        with:      
          token: ${{ github.token }}
          branches: |
            main
            stage
       
      # merge github dev to stage
      - name: Cascading Merge2
        uses: sovabarmak/cascading-merge-action@v1.0.10
        with:
          branches: |
            main
            dev
      