name: Deploy to WP Engine and push to dev and live
on:
  push:
    branches:
     - main
jobs:
  cascading-merge:
    name: Cascading Merge
    runs-on: ubuntu-latest
    steps:
      - name: Cascading Merge
        uses: mheap/cascading-merge-action@v1
        with:
          branches: |
            main
            stage