name: Deploy to WP Engine
on:
  push:
    branches:
     - main
jobs:
  cascading-merge:
    permissions: write-all
    name: Cascading Merge
    runs-on: ubuntu-latest
    steps:
      # merge github main to stage
      - name: Cascading Merge
        uses: mheap/cascading-merge-action@v1.0.1
        with:      
          token: ${{ github.token }}
          branches: |
            main
            stage
       
      # merge github dev to stage
      - name: Cascading Merge2
        uses: mheap/cascading-merge-action@v1.0.1
        with:
          branches: |
            main
            dev
      - name: Failed Cascade merge
      - uses: JasonEtco/create-an-issue@v2
        with:
          title: Someone just pushed
          assignees: ${{GITHUB_ACTOR}}