name: Deploy to WP Engine and push to dev and live
on:
  push:
    branches:
     - main
jobs:
  cascading-merge:
    name: Cascading Merge
    runs-on: ubuntu-latest
    steps:
      - name: Cascading Merge
        uses: mheap/cascading-merge-action@v1.0.1
        with:
          # Changes to `branch-1` will automatically be merged into `branch-2` and `branch-3`
          branches: |
            main
            stage
          token: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}